id: event_file_ingest
namespace: gcp.yellowcab

variables:
  project: "kestra-workspace-ak-lde-2025"
  dataset: "YellowCab"

triggers:

  - id: gcs_event_trigger
    type: io.kestra.plugin.gcp.pubsub.RealtimeTrigger
    projectId: "kestra-workspace-ak-lde-2025"
    topic: "file-upload-events"
    subscription: "file-upload-sub"
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT') }}"
    autoCreateSubscription: false
    maxRecords: 1

tasks:

  - id: log_event
    type: io.kestra.plugin.core.debug.Return
    format: |
      Received Event:
      Bucket: {{ trigger.attributes.bucketId }}
      File:   {{ trigger.attributes.objectId }}

  - id: load_raw
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT') }}"
    from:
      - "gs://{{ trigger.attributes.bucketId }}/{{ trigger.attributes.objectId }}"
    destinationTable: "{{ vars.project }}.{{ vars.dataset }}.pub_sub_raw"
    format: PARQUET
    writeDisposition: WRITE_APPEND

errors:
  - id: on_error
    type: io.kestra.plugin.core.debug.Return
    format: |
      ERROR during RAW ingest:
      Bucket: {{ trigger.attributes.bucketId }}
      File:   {{ trigger.attributes.objectId }}