models:
  - name: stg_green_tripdata
    description: >
      Staging model for green taxi trip data. Standardizes column names
      and data types from the raw green_tripdata source.
    columns:
      - name: vendor_id
        description: Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.)
        data_tests:
          - not_null
      - name: rate_code_id
        description: Rate code at end of trip (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
      - name: pickup_location_id
        description: TLC Taxi Zone where the meter was engaged
      - name: dropoff_location_id
        description: TLC Taxi Zone where the meter was disengaged
      - name: pickup_datetime
        description: Date and time when the meter was engaged
        data_tests:
          - not_null
      - name: dropoff_datetime
        description: Date and time when the meter was disengaged
      - name: store_and_fwd_flag
        description: Flag indicating if trip record was held in vehicle memory (Y/N)
      - name: passenger_count
        description: Number of passengers in the vehicle
      - name: trip_distance
        description: Trip distance in miles
      - name: trip_type
        description: Code for trip type (1=Street-hail, 2=Dispatch)
      - name: fare_amount
        description: Time and distance fare
      - name: extra
        description: Miscellaneous extras and surcharges
      - name: mta_tax
        description: $0.50 MTA tax
      - name: tip_amount
        description: Tip amount (credit card tips only)
      - name: tolls_amount
        description: Total tolls paid
      - name: ehail_fee
        description: E-hail service fee
      - name: improvement_surcharge
        description: Improvement surcharge
      - name: total_amount
        description: Total amount charged to passengers
      - name: payment_type
        description: Payment method code (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)

  - name: stg_yellow_tripdata
    description: >
      Staging model for yellow taxi trip data. Standardizes column names
      and data types from the raw yellow_tripdata source.
    columns:
      - name: vendor_id
        description: Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.)
        data_tests:
          - not_null
      - name: rate_code_id
        description: Rate code at end of trip
      - name: pickup_location_id
        description: TLC Taxi Zone where the meter was engaged
      - name: dropoff_location_id
        description: TLC Taxi Zone where the meter was disengaged
      - name: pickup_datetime
        description: Date and time when the meter was engaged
        data_tests:
          - not_null
      - name: dropoff_datetime
        description: Date and time when the meter was disengaged
      - name: store_and_fwd_flag
        description: Flag indicating if trip record was held in vehicle memory (Y/N)
      - name: passenger_count
        description: Number of passengers in the vehicle
      - name: trip_distance
        description: Trip distance in miles
      - name: fare_amount
        description: Time and distance fare
      - name: extra
        description: Miscellaneous extras and surcharges
      - name: mta_tax
        description: $0.50 MTA tax
      - name: tip_amount
        description: Tip amount (credit card tips only)
      - name: tolls_amount
        description: Total tolls paid
      - name: improvement_surcharge
        description: Improvement surcharge
      - name: total_amount
        description: Total amount charged to passengers
      - name: payment_type
        description: Payment method code (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)

  - name: stg_fhv_tripdata
    description: >
      Staging model for For-Hire Vehicle (FHV) trip data (2019).
      FHV includes Uber, Lyft, and other livery/black car services.
      Filters out records with null dispatching_base_num and standardizes column names.
    columns:
      - name: dispatching_base_num
        description: TLC base license number of the dispatching base
        data_tests:
          - not_null
      - name: affiliated_base_number
        description: TLC base license number of the affiliated base
      - name: pickup_location_id
        description: TLC Taxi Zone where the trip started
      - name: dropoff_location_id
        description: TLC Taxi Zone where the trip ended
      - name: pickup_datetime
        description: Date and time of the trip pickup
        data_tests:
          - not_null
      - name: dropoff_datetime
        description: Date and time of the trip dropoff
      - name: shared_ride_flag
        description: "Shared ride indicator (1 = shared ride, null = not shared)"
